### ISSUE TITLE
dropbox -> Dropbox

### ISSUE THREAD

**Issue by philsturgeon** [jimdoescode/CodeIgniter-Dropbox-API-Library#1]
Not sure if this is the repo you use for the Spark but I am way too tired of fixing bugs to fix this one for you with a pull request, sorry.

```
$ git mv sparks/dropbox/1.1.3/libraries/dropbox.php sparks/dropbox/1.1.3/libraries/dropbox.php.tmp
$ git mv sparks/dropbox/1.1.3/libraries/dropbox.php.tmp sparks/dropbox/1.1.3/libraries/Dropbox.php
```

Lower-case will break case sensitive file systems.

**Comment by jimdoescode** [comment]
You are going to have to be more descriptive than that. Is this an issue that only happens on sparks? What file systems are the problems? Is it a CI issue? What steps are involved in reproducing the issue? Error output? 

I realize it's an easy fix to make but I would like more info as this is the first I am hearing about anyone having problems like this, also it effect the other API libraries I have.

[EDIT] It's not that I am unwilling to make the change I just want to understand the catalyst behind it.

**Comment by philsturgeon** [comment]
Fair enough!

First name is a CodeIgniter naming convention.

```
Naming Conventions

File names must be capitalized. For example:  Myclass.php
```

It will try to load "Dropbox.php" which on most filesystems (case in-sensitive file systems) is fine. MAMP, CentOS, etc all out of the box are case in-sensitive. If you put this on Ubuntu or whatever file system Pagoda Box is running you'll get errors.

This needs to be changed for every single Spark you have. All libraries must be upper cased.

**Comment by jimdoescode** [comment]
Gotcha, I just noticed that in the docs. I will make the changes ASAP. Thanks for the heads up.

**Comment by jimdoescode** [comment]
Fixed in latest commit.
