### ISSUE TITLE
i am not able to upload file

### ISSUE THREAD

**Issue by Ayyappa-amara** [jimdoescode/CodeIgniter-Dropbox-API-Library#10]
i am not able to upload file into dropbox 
and i am not getting any error just blank page is displaying...

i have written like this

$dbobj = $this->dropbox->add("folder_name","filename.pdf", $params, "sandbox");

please solve my problem any one.

**Comment by jimdoescode** [comment]
I just tested adding files to dropbox and it seems to be working fine. Please set the DEBUG const to true and monitor your php error log for a better understanding about what is going on.

**Comment by Kendysond** [comment]
Please don't promote your own libraries here. - Jimdoescode
