### ISSUE TITLE
Upload Issue

### ISSUE THREAD

**Issue by mystx** [jimdoescode/CodeIgniter-Dropbox-API-Library#11]
Hi,

I am having an issue when using 
$dbobj = $this->dropbox->add("clients","test.txt", $params, "sandbox");
var_dump($dbobj) gives me the message "NULL"

Please help

Thanks
Jason

**Comment by mystx** [comment]
I have found this in my php log file

[16-Aug-2013 11:44:29 Europe/Berlin] {"error": "Invalid signature."}

**Comment by jimdoescode** [comment]
Try setting the DEBUG const in the library to true. That will write detailed information about the request and response to and from the dropbox api to the default PHP error log. I will test this out when I get home but I suspect it's a configuration issue.

**Comment by jimdoescode** [comment]
Tested this and it's working fine. You must have some configuration issue. Please refer to my previous comment for help in diagnosing the problem.

**Comment by Kendysond** [comment]
Please don't promote your own libraries here. - Jimdoescode
