### ISSUE TITLE
undefined index : oauth_token

### ISSUE THREAD

**Issue by applemate** [jimdoescode/CodeIgniter-Dropbox-API-Library#14]
Hi Jim,

Upon test the drive exmaple/request dropbox I got these error:

```A PHP Error was encountered

Severity: Notice

Message: Undefined index: oauth_token

Filename: libraries/Dropbox.php

Line Number: 118

A PHP Error was encountered

Severity: Notice

Message: Undefined index: oauth_token_secret

Filename: libraries/Dropbox.php

Line Number: 120```

**Comment by jimdoescode** [comment]
Did you fill in your key and secret from Dropbox?

**Comment by applemate** [comment]
Do I have to? Where can I get consumer key and secret? I tried to find it in my dropbox account, but nothing.

**Comment by jimdoescode** [comment]
Yes, you have to. Create a new app here: https://www.dropbox.com/developers/apps then that will give you an App Key and App Secret you can use.

I'm going to close this ticket since everything seems to be working correctly on my end.

**Comment by applemate** [comment]
I got the key and secret filled, still have the same error. I made a few seconds video demo, you can check out what's really happen.

https://www.dropbox.com/s/g9py5cmurfzn6nu/error.mp4?dl=0

**Comment by jimdoescode** [comment]
The code looks fine. I'd check what the response is from Dropbox. You can enable logging in the library by going to Dropbox.php and setting the DEBUG constant to true. That will write all the request and response data to and from Dropbox to the standard PHP error log. That should tell you why Dropbox isn't issuing an access token.

**Comment by applemate** [comment]
Ok then I got this:

[02-Apr-2015 09:49:15 America/Chicago] 
[02-Apr-2015 09:50:07 America/Chicago] Array
(
    [url] => https://api.dropbox.com/1/oauth/request_token
    [content_type] => 
    [http_code] => 0
    [header_size] => 0
    [request_size] => 0
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0
    [namelookup_time] => 0.000938
    [connect_time] => 0.048911
    [pretransfer_time] => 0
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0
    [redirect_time] => 0
    [certinfo] => Array
        (
        )

```
[primary_ip] => 108.160.161.147
[redirect_url] => 
```

)

[02-Apr-2015 09:50:07 America/Chicago]

**Comment by jimdoescode** [comment]
For some reason PHP can't connect to Dropbox. Do you have cURL installed? I'd start xdebug and step through the project that will give you the best picture of what is going on. 

Also what version are you using? Do you have the proper certs that come with the library?

**Comment by applemate** [comment]
I'm on a share host (hostgator to be exact) Not sure if I have cURL. Codeigniter version is 2.1.4. The cert folder comes with api package has been copied to library folder.

If to debug, what clue should I be looking for?

**Comment by applemate** [comment]
could it be the config of my dropbox app?

Here are some screenshots of drop app console

https://www.dropbox.com/s/7mcszo9rg3rw1lu/scrren1.png?dl=0

https://www.dropbox.com/s/07utoqrx9l7r12l/screen2.png?dl=0

**Comment by jimdoescode** [comment]
You can run phpinfo() and see what the response is. I'd recommend working on a local server instead of your shared host. That will make debugging easier. 

Also just a heads up, once you get everything working change your key and secret since everyone on GitHub can see them now.

**Comment by applemate** [comment]
I screenshot the phpinfo on the server. Here it is

https://www.dropbox.com/s/fz5bxlb2ceuitm0/phpinfo%28%29.html?dl=0

**Comment by applemate** [comment]
Hey I just tried on localhost, it works great. So what would be the server's problem?

**Comment by applemate** [comment]
However on the local, after the very first authorizing, I got this error

https://www.dropbox.com/s/3g8n5uv5xwa11al/Screen%20Shot%202015-04-03%20at%2012.31.55%20AM.png?dl=0

**Comment by jimdoescode** [comment]
Sounds like your host is preventing you from connecting to dropbox. Those errors you're seeing locally are because the example is outputing data before CodeIgniter has written any header information.

**Comment by jimdoescode** [comment]
Talk to your host provider and see what they can do. You've proven that the library works and there is nothing in the code that would prevent it from working on other servers.

**Comment by applemate** [comment]
thanks for the heads up. Definitely got to do something about it

**Comment by craigcosmo** [comment]
Can you do me a favor, remove the comments about credential and github. :)

**Comment by jimdoescode** [comment]
You should be able to delete any of your own comments.

**Comment by craigcosmo** [comment]
I mean yours. no one would know it unless you mention it publicly.

**Comment by jimdoescode** [comment]
I'd like to keep the chat history incase anyone comes along with your similar issue. I've edited the comment to remove the offending statement but you should really remove that stuff.

**Comment by Kendysond** [comment]
Please don't promote your own libraries here. - Jimdoescode
