### ISSUE TITLE
Upload File Issue

### ISSUE THREAD

**Issue by nealhowarth** [jimdoescode/CodeIgniter-Dropbox-API-Library#17]
Hi

I seem to be having an issue trying to upload a file to Dropbox.
I have tested the connection and it all works fine; it returns the account details etc.
I have enabled debugging, but I don't actually seem to be getting any error messages in the logs, but the add() function is returning some data:

`[Wed Jun 24 11:44:31 2015] [error] [client 87.127.109.10] POST /files/dropbox/Portal%20Archive/Telephone%20Directory-Sep14.pdf?file=https%3A%2F%2Fsandbox.arithmoportal.co.uk%2Fuploads%2FACC4%2F678aeb901b8fcc37375e53f52f802a72.pdf HTTP/1.1\r\nHost: api-content.dropbox.com\r\nConnection: close\r\nUser-Agent: CodeIgniter\r\nAccept-encoding: identity\r\nAuthorization: OAuth oauth_consumer_key="q78w7fnkpm99t2o", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1435146271", oauth_nonce="2eea3967328c2b2091baaf09b1243e72", oauth_version="1.0", oauth_token="el5hi7ku7d7dvspw", oauth_signature="a4h8qTlZmmov35MYzXmtyRHZSTI%3D"\r\n\r\n`

`[Wed Jun 24 11:44:31 2015] [error] [client 87.127.109.10] Array\n(\n    [url] => https://api-content.dropbox.com/1/files/dropbox/Portal%20Archive/Telephone%20Directory-Sep14.pdf?file=https%3A%2F%2Fsandbox.arithmoportal.co.uk%2Fuploads%2FACC4%2F678aeb901b8fcc37375e53f52f802a72.pdf\n    [content_type] => \n    [http_code] => 0\n    [header_size] => 0\n    [request_size] => 0\n    [filetime] => -1\n    [ssl_verify_result] => 0\n    [redirect_count] => 0\n    [total_time] => 0.251891\n    [namelookup_time] => 0.012708\n    [connect_time] => 0.086594\n    [pretransfer_time] => 0.251826\n    [size_upload] => 0\n    [size_download] => 0\n    [speed_download] => 0\n    [speed_upload] => 0\n    [download_content_length] => -1\n    [upload_content_length] => -1\n    [starttransfer_time] => 0\n    [redirect_time] => 0\n    [certinfo] => Array\n        (\n        )\n\n    [primary_ip] => 23.23.97.3\n    [redirect_url] => \n)\n`

Any advice appreciated.

Thanks

**Comment by jimdoescode** [comment]
It looks like you are trying to upload a link not a file. The comment block for the API lib states 

`$filepath The relative path on the server of the file to upload.`

So make sure that you are uploading a file on your local server.

I'm closing this as I tested the API and it's working as expected. We can continue to trouble shoot any issues in this thread though.
