### ISSUE TITLE
Url Encode Special Chars in path

### ISSUE THREAD

**Issue by 72quadrat** [jimdoescode/CodeIgniter-Dropbox-API-Library#2]
There are only white spaces in filenames or foldernames url encoded like this:
$path = str_replace(' ', '%20', $path);

so folders or filenames with umlauts, or other special characters won't work
better do it this way the other way around:
$path = str_replace('%2F', '/', urlencode($path));

What it does it, that everything get's urlencoded and after it the slashes get back to real slashes.

I had big issues with german umlauts in filenames.

**Comment by jimdoescode** [comment]
I kept meaning to do this but haven't had the time. Would you mind creating a pull request with your fix?
