### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by hakimihamdan88** [jimdoescode/CodeIgniter-Dropbox-API-Library#6]
use Codeigniter `log_message('debug', $header);` instead `error_log($header);`

**Comment by jimdoescode** [comment]
This is a good suggestion. However I want to keep logging separate from CI it keeps the lib more portable to other frameworks.

**Comment by hakimihamdan88** [comment]
if you want portable, dont use as "Codeigniter Dropbox API Library" and $this->CI =& get_instance(); ;)

**Comment by jimdoescode** [comment]
If you actually looked at the library code the only CI related code I use is the reduce_double_slashes method found in the string helper. If you write a replacement for that then there is absolutely no need to get a CI instance. That's the way I would like to keep it. Further tying the library into CodeIgniter is unnecessary.
