### ISSUE TITLE
return value of _content_request is missing

### ISSUE THREAD

**Issue by skinit** [jimdoescode/CodeIgniter-Dropbox-API-Library#7]
private function _content_request($uri, $destination) does not return a value. so in case of $destination===false the response of _connect is lost. this function should return the return value of the _connect call. otherwise the case of $destination===false is useless.

**Comment by jimdoescode** [comment]
That's a good point _content_request does need to return something. However returning the result of the _connect function is not the correct thing to return. The reason is that for a content request the return value of the _connect function is the data of the file requested. 

Maybe _connect should be altered to return a boolean for content requests. I think that would solve the issue you are seeing.

**Comment by jimdoescode** [comment]
OK it should be fixed. _content_request will now return a boolean value based on success. Thanks for pointing out the issue.

**Comment by skinit** [comment]
Hello Jim, 
the idea was to be able to use "dropbox->get" without being forced to save the get-result into a "destination" file (using $destination===false). Thats why _content_request should return the curl "$response" (at least in this case). This way one could use "dropbox->get" to assign a variable without file interaction. With your latest change this is not possible. Maybe there should be a alternative "dropbox->getbuffer" instead.

**Comment by jimdoescode** [comment]
Oh I see. Yes I would think that would warrant a separate method. I had never considered the possibility of someone wanting to do that but now that you mention it it's a pretty compelling idea. I'll look into adding something along those lines.

**Comment by skinit** [comment]
Thank you Jim .. that would be great

**Comment by jimdoescode** [comment]
I was just looking back over the code for some changes I'm making to the library. I just tested this and in the current version if you want to get file contents all you need to do is pass false in the destination field of the get method.

``` php
$this->dropbox->get(false, '/Dropbox/file.jpg');
```

That should get you the actual contents of "file.jpg" as a string. I think you already mentioned that but I just wanted to confirm it.

**Comment by skinit** [comment]
Sorry for the delay, I checked your latest version and it works fine for me ... thank you for adding buffer support.
