### ISSUE TITLE
Unable to upload

### ISSUE THREAD

**Issue by fibericon** [jimdoescode/CodeIgniter-Dropbox-API-Library#9]
Everything seems to work in the example controller, and I get the user data no problem. However, when I try to upload something, I get the very nondescript error text, "Forbidden". My app only has access to one folder. I've tried the add() call a few different ways: full path to the app's folder, empty quotes, and just the file name. They all return the same thing, and without any real error text, I can't debug it. I know the error text is generated on dropbox's end, but I'm hoping you all know a way around this problem, or at least know what could cause it.

**Comment by jimdoescode** [comment]
You can turn on some logging by setting the DEBUG const to true in the library. That will write more detailed information to the default PHP error log. 

I just ran some tests and found no issues with the current upload functionality. Would you mind posting your code?

**Comment by fibericon** [comment]
Setting the debug const to true seemed to have no impact on the error text. For my code, I'm using the example controller, with the exception of adding my own keys. Also, in test_dropbox(), I have this, directly after $dbobj = $this->dropbox->account():

var_dump($this->dropbox->add("cards.pdf", getcwd()."/assets/pdf/1.pdf"));

That produces this:

object(stdClass)#18 (1) { ["error"]=> string(9) "Forbidden" }

**Comment by jimdoescode** [comment]
The DEBUG flag does not change the error text. It logs debug information to the PHP error log you need to check your log. That said have you tried "/cards.pdf" as the path on the dropbox?

**Comment by fibericon** [comment]
I've tried "/cards.pdf" as well. Here's what that got me in the log:

[06-May-2013 21:07:30] Array
(
    [url] => https://api-content.dropbox.com/1/files/dropbox/cards.pdf?file=%2Fhome%2Frebelwar%2Fpublic_html%2Fcards%2Fassets%2Fpdf%2F1.pdf
    [content_type] => application/json
    [http_code] => 403
    [header_size] => 182
    [request_size] => 636
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.596009
    [namelookup_time] => 0.002087
    [connect_time] => 0.039729
    [pretransfer_time] => 0.14853
    [size_upload] => 26004
    [size_download] => 22
    [speed_download] => 36
    [speed_upload] => 43630
    [download_content_length] => -1
    [upload_content_length] => 26004
    [starttransfer_time] => 0.1883
    [redirect_time] => 0
    [request_header] => POST /1/files/dropbox/cards.pdf?file=%2Fhome%2Frebelwar%2Fpublic_html%2Fcards%2Fassets%2Fpdf%2F1.pdf HTTP/1.1

Accept: _/_

Host: api-content.dropbox.com

Connection: close

User-Agent: CodeIgniter

Accept-encoding: identity

Authorization: OAuth oauth_consumer_key="['key removed]", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1367892450", oauth_nonce="192e8ad710a53308b6d39d6a31a9e956", oauth_version="1.0", oauth_token="l32csjssl11na9u", oauth_signature="otUSurC7ap59wv1KdzP%2FTiz6clc%3D"

Content-Length: 26004

Expect: 100-continue

Content-Type: multipart/form-data; boundary=----------------------------82582d314e22

)

[06-May-2013 21:07:30] {"error": "Forbidden"}

**Comment by jimdoescode** [comment]
What type of app did you register? Is it "Full Dropbox" or "App Folder"? The DEFAULT_ROOT parameter if you didn't change it is for Full Dropbox. You will need to make sure the DEFAULT_ROOT matches the app type you register.

**Comment by fibericon** [comment]
It was "App folder". Looks like you nailed the problem - switching DEFAULT_ROOT to "sandbox" did the trick. Thanks for the help.

**Comment by Kendysond** [comment]
Please don't promote your own libraries here. - Jimdoescode
